kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: default
  labels:
    {{- with .Values.tags }}
    first: {{ .machine }}
    second: {{ .rack }}
    third: {{ .drive }}
    {{- end }}
data:
  myvalue: "Sample Config Map"
  costCode: {{ .Values.costCode }}
  Zone: {{ quote .Values.infra.zone }}
  Region: {{ quote .Values.infra.region }}
  ProjectCode: {{ upper .Values.projectCode }}
  {{- with .Values.tags }}
  Machine_Type: {{ .machine | default "NA" | quote }}
  Rack_ID: {{ .rack | quote }}
  Storage_Type: {{ .drive | upper | quote }}
  Video_Card: {{ .vcard | quote }}
  {{- end }}