kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: default
data:
  myvalue: "Sample Config Map"
  costCode: {{ .Values.costCode }}
  ProjectCode: {{ upper .Values.projectCode }}
  Zone: {{ quote .Values.infra.zone }}
  Region: {{ quote .Values.infra.region }}
  {{- if eq .Values.infra.region "us-e" }}
  ha: true 
  {{- end }}