kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: default
data:
  myvalue: "Sample Config Map"
  costCode: {{ .Values.costCode }}
  ProjectCode: {{ upper .Values.projectCode }}
  Zone: {{ quote .Values.infra.zone }}
  Region: {{ quote .Values.infra.region }}
  Pipeline: {{ .Values.projectCode | upper | quote }}
  now: {{ now | date "2006-01-02" | quote }}
  contact: {{ .Values.contact | default "1-800-123-0000" | quote }}